from enum import Enum


class SocketState(Enum):
    RECIEVING_COMMANDS = 1
    RECIEVING_OBJECT_SHAPE = 2
    RECIEVING_OBJECT_DATA = 3
    RECIEVING_OBJECT_NAME = 4
    SEND_OBJECT_DATA = 5
    SKIP_OBJECT = 6
    RECIEVING_OBJECT_SHAPE_SIZE = 7
